the second task is fp
eoll73/ru-study-ruby pull request #2
Opened 2022-10-07 15:08 UTC by eoll73

2022-10-07 15:41 UTC, greybutton requested changes

2022-10-07 15:41 UTC, greybutton commented on test/exercise/fp/solution.rb
> +        ratings_of_interest = array.each_with_object([]) do |film, acc|
почему each_with_object?

2022-10-07 15:41 UTC, greybutton commented on test/exercise/fp/solution.rb
> +      def multiple?(string)
не слишком очевидная функция по ментальному программированию

2022-10-07 15:41 UTC, greybutton commented on test/exercise/fp/solution.rb
> +        end.compact
давай уберем вложенность

2022-10-07 19:45 UTC, eoll73 commented on test/exercise/fp/solution.rb
> +        ratings_of_interest = array.each_with_object([]) do |film, acc|
сам не знаю  что  это  и откуда  взялось. Непостижимым образом  линтер "docker-compose run --rm ruby bundle exec rubocop -A" полностью ломает , перестраивает  код  как  ему заблагорассужится.  Эту часть" each_with_object" я никогда не  писал

2022-10-08 09:51 UTC, greybutton requested changes

2022-10-08 09:51 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        -1
код из другого задания

2022-10-08 13:09 UTC, eoll73 commented
бред какой-то

2022-10-08 13:09 UTC, closed without merging