first commit
eoll73/ru-study-ruby pull request #4
Opened 2022-10-13 18:31 UTC by eoll73

2022-10-13 18:33 UTC, eoll73 commented
2 часть переписал как было велено , с рекурсией

2022-10-14 06:14 UTC, greybutton requested changes

2022-10-14 06:14 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +          return array[middle] < query ? self.search(array, query, middle, last)
почему через self? без него не работает?

2022-10-14 06:14 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        (0..array.length - 1).each do |index|
почему через индекс меняется элемент?

2022-10-14 09:10 UTC, eoll73 commented on test/exercise/arrays/solution.rb
> +        (0..array.length - 1).each do |index|
не понимаю вопрос *( всё работает , тесты проходят....

2022-10-14 14:10 UTC, greybutton approved these changes

2022-10-14 14:43 UTC, merged